apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: c1
      image: centos
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: podvol
          mountPath: "/tmp/c1dir"

    - name: c2
      image: centos
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: podvol
          mountPath: "/tmp/c2dir"
  volumes:
    - name: podvol
      emptyDir: {}

