apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: c01
      image: centos
      command: ["/bin/bash", "-c", "sleep 15000"]
      volumeMounts:
        - mountPath: /tmp/contdir
          name: testvolume
  volumes:
    - name: testvolume
      hostPath:
        path: /tmp/hostdir

