apiVersion: v1
kind: Pod
metadata:
  name: yamlenvsecret
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-Subhash; sleep 5; done"]
    env:
    - name: MYENVUSER
      valueFrom:
        secretKeyRef:
          name: myyamlsecret
          key: myname
