apiVersion: v1
kind: Pod
metadata:
  name: myvolconfig
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-Subhash; sleep 5; done"]
    volumeMounts:
    - name: testconfigmap
      mountPath: "/tmp/config"  # Corrected indentation here
  volumes:
  - name: testconfigmap
    configMap:
      name: mymap
      items:
      - key: samplefile
        path: samplefile

